language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - 7

before_script:
    - composer install

before_script:
    - curl -s https://getcomposer.org/installer | php
    - php composer.phar update --dev --no-interaction
    - mkdir -p build/logs

script:
    - php vendor/bin/phpunit --coverage-text
