language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - 7

before_install:
    - composer self-update

install:
    - composer install --prefer-source

script:
    - ./vendor/bin/phpunit --coverage-text
